---
apiVersion: "apps/v1"
kind: "Deployment"
metadata:
  name: "nabil-app"
  namespace: "default"
  labels:
    app: "nabil"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: "nabil"
  template:
    metadata:
      labels:
        app: "nabil"
    spec:
      containers:
      - name: "python-app"
        image: "ahmednabilsharawy/hello_nabil:1"
---
apiVersion: v1
kind: Service
metadata:
  name: my-alb
  namespace: default   
spec:
  selector:
    app: nabil
  ports:
    - port: 80
      targetPort: 5000
  type: LoadBalancer


